### ISSUE TITLE
API - Phyton 400 error when running a Product Database Query in DE marketplace

### ISSUE THREAD

**Issue by franzJS00** [Junglescout/junglescout-python-client#76]
Describe the bug
The customer is getting a 400 error when running a PD endpoint query on Phyton. The parameters are correct, and it appears to be isolated to the DE marketplace only

Paulo has confirmed the bug. 
 
 
API code & error: 
 
HTTP ERROR: 400 Client Error: Bad Request for URL:
 
Troubleshooting steps
N/A 
Screenshots:

<img width="1238" alt="Screenshot 2024-06-10 at 13 05 54" src="https://github.com/Junglescout/junglescout-python-client/assets/171689370/17aa529c-3490-4814-9dcd-c3456e5405eb">
<img width="308" alt="Screenshot 2024-06-10 at 13 26 26" src="https://github.com/Junglescout/junglescout-python-client/assets/171689370/53bceac5-e52a-4846-8371-e1b938fbfb6b">

 
Additional information (optional)
<img width="675" alt="Screenshot 2024-06-10 at 13 24 15" src="https://github.com/Junglescout/junglescout-python-client/assets/171689370/454915e6-59b0-4363-a74c-2789dfc7398a">

**Comment by salimhamed** [comment]
Hi @franzJS00! Thanks for submitting this bug report. Commenting to let you know we've received it and we're looking into it.

**Comment by salimhamed** [comment]
@franzJS00 let us know if your issue is resolved in [v0.2.0](https://github.com/Junglescout/junglescout-python-client/releases/tag/v0.2.0).
