### ISSUE TITLE
ValidationError caused by updated_at in keyword_by_asin

### ISSUE THREAD

**Issue by heidenfuerst** [Junglescout/junglescout-python-client#82]
I got ValidationErrors quite often, when trying to fetch keywords with the keyword_by_asin function, where updated_at was not in a valid datetime format.

`[WARNING]	2024-07-19T11:26:20.539Z	a94cad88-58f5-4866-80d2-5a6cc79a6988	Validation error for ASIN B07CP9HXQ2: 1 validation error for APIResponse[List[junglescout.models.responses.keyword_by_asin.KeywordByASIN]]
data.43.attributes.updated_at
  Input should be a valid datetime [type=datetime_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.8/v/datetime_type`

Fixed it by making the updated_at optional too:

`# updated_at: datetime = Field(default=..., description="The date the keyword was last updated.")  # OLD
    updated_at: Optional[datetime] = Field(default=None, description="The date the keyword was last updated.")  # NEW`

Hope this helps as I'm probably not the only one with this problem.

**Comment by salimhamed** [comment]
Hi @heidenfuerst! Thanks for submitting this issue. We're planning to look into this and most likely will update the validation rules. Stay tuned!
